<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Generate detailed Audit Logs for MVC Controller actions.</Description>
        <Copyright>Copyright 2016</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.Mvc</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>TRACE;DEBUG</DefineConstants>
        <NoWarn>$(NoWarn);1591;NETSDK1138</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.Mvc</AssemblyName>
        <PackageId>GoLive.SaturnAudit.Mvc</PackageId>
        <PackageTags>Audit;Trail;Log;MVC;ActionFilter</PackageTags>
        <PackageIcon>icon.png</PackageIcon>
        <PackageProjectUrl>https://github.com/thepirat000/Audit.NET</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/thepirat000/Audit.NET</RepositoryUrl>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(DefineConstants);ASP_CORE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.1"/>
        <PackageReference Include="System.Runtime" Version="4.3.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="images\icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
