<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
	  <NoWarn>$(NoWarn);1591;NETSDK1138</NoWarn>
	  <IsPackable>false</IsPackable>
	  <IsTestProject>true</IsTestProject>
	  <DefineConstants>$(DefineConstants)</DefineConstants>
	  <SignAssembly>true</SignAssembly>
	  <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
	  <AssemblyOriginatorKeyFile>../../src/StrongName/Audit.NET.UnitTests.snk</AssemblyOriginatorKeyFile>
	  <DebugType>Full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Audit.NET.Firestore\Audit.NET.Firestore.csproj" />
    <ProjectReference Include="..\..\src\Audit.NET\Audit.NET.csproj" />
  </ItemGroup>

</Project> 