<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Description>Log Audit.NET Audit Trail Polly™</Description>
        <Copyright>Copyright 2024</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.Polly</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.NET.Polly</AssemblyName>
        <PackageId>GoLive.SaturnAudit.NET.Polly</PackageId>
        <PackageTags>Audit;Trail;Log;Polly</PackageTags>

        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>

        <Nullable>enable</Nullable>
        <RootNamespace>Audit.Polly</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Polly.Core" Version="8.3.0"/>
    </ItemGroup>
</Project>
