<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Generate Audit Logs from file system events using a FileSystemWatcher</Description>
        <Copyright>Copyright 2018</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.FileSystem</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.FileSystem</AssemblyName>
        <PackageId>GoLive.SaturnAudit.FileSystem</PackageId>
        <PackageTags>Audit;File System;Log;FileSystemWatcher</PackageTags>
        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <NetStandardImplicitPackageVersion Condition=" '$(TargetFramework)' == 'netstandard2.0' ">2.0.3</NetStandardImplicitPackageVersion>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="System.Text.Json" Version="9.0.4"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>
</Project>