<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Description>Log Audit.NET Audit Trail NLog™</Description>
        <Copyright>Copyright 2019</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.NLog</AssemblyTitle>
        <Authors>Dominick Marciano</Authors>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.NET.NLog</AssemblyName>
        <PackageId>GoLive.SaturnAudit.NET.NLog</PackageId>
        <PackageTags>Audit;Trail;Log;NLog</PackageTags>
        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>

        <RootNamespace>Audit.NLog</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE"/>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NLog" Version="5.2.7"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="images\icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
