<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Generate Audit Logs by intercepting operation calls on any class without changing its code.</Description>
        <Copyright>Copyright 2019</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.DynamicProxy</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <Authors>Federico Colombo</Authors>
        <TargetFramework>netstandard2.0</TargetFramework>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>1701;1702;1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.DynamicProxy</AssemblyName>
        <PackageId>GoLive.SaturnAudit.DynamicProxy</PackageId>
        <PackageTags>Audit;Trail;Log;Proxy;Castle;DynamicProxy</PackageTags>
        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <NetStandardImplicitPackageVersion Condition=" '$(TargetFramework)' == 'netstandard2.0' ">2.0.3</NetStandardImplicitPackageVersion>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="5.1.1"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0"/>
    </ItemGroup>
</Project>
