<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Description></Description>
        <Copyright>Copyright 2024</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.Channels</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>GoLive.SaturnAudit.NET.Channels</AssemblyName>
        <PackageId>GoLive.SaturnAudit.NET.Channels</PackageId>
        <PackageTags>Audit;Trail;Log;Channels</PackageTags>
        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>

        <Nullable>enable</Nullable>
        <RootNamespace>Audit.Channels</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.Threading.Channels" Version="9.0.0"/>
    </ItemGroup>
</Project>
