<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Generate detailed Audit Logs for gRPC client calls.</Description>
        <Copyright>Copyright 2025</Copyright>
        <AssemblyTitle>GoLive.Saturn.Audit.Grpc.Client</AssemblyTitle>
        <Authors>Federico Colombo</Authors>
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyName>Golive.Saturn.Audit.Grpc.Client</AssemblyName>



        <PackageId>Golive.Saturn.Audit.Grpc.Client</PackageId>
        <PackageTags>Audit;Trail;Log;Grpc</PackageTags>

        <PackageProjectUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/surgicalcoder/GoLive.Saturn.Audit.NET</RepositoryUrl>

    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE"/>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Audit.NET\Audit.NET.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Core.Api" Version="2.71.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="images\icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
